### ISSUE TITLE
DEVMODE warnings / footguns

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/domvm#135]
~~there is no DEVMODE, but perhaps there will be in the future [1]. this is a list of footguns which can perhaps be detected:~~

there *is* devmode!

- [x] redrawing an unmounted subview (https://github.com/leeoniya/domvm/issues/131)
- [x] simultaneous `input[type=...]` & `value` mutation (https://github.com/leeoniya/domvm/issues/134)
- [x] view auto-keying by model (https://github.com/leeoniya/domvm/issues/130).
- [x] model replacement
- [x] ~~too-frequent mount/unmounts, or removes/re-inserts (poor dom-recycling behavior)~~ handled by mutation logging
- [x] `<svg>` is accidentally defined via `defineElement` rather `defineSvgElement`
- [x] differing event handler def styles (cannot be always be patched)
- [x] inline event handler defs (will get re-bound on each redraw)
- [x] adjacent textNode merging (perf)
- [x] array flattening (perf)
- [ ] injecting a vm that's already mounted elsewhere

should be handled by typings:

- [ ] returning non-vnode things from render()
- [ ] view must return function or object
- [ ] render must return VNode

[1] https://github.com/leeoniya/domvm/issues/131#issuecomment-300071448

**Comment by leeoniya** [comment]
@tropperstyle it looks like this is game on. The current Closure Compiler version properly dead-code-eliminates the following even in `SIMPLE_OPTIMIZATIONS` mode:

```js
const DEVMODE = false;

if (DEVMODE) {
 ...
}
```

**Comment by leeoniya** [comment]
turns out Rollup can do basic DCE, so now we have an official DEVMODE build! Demo [1].

i've added some warnings [2 for unkeyed inputs and if `<svg>` is accidentally defined via `defineElement` rather `defineSvgElement`.

[1] https://github.com/leeoniya/domvm/blob/2.x-dev/demos/devmode.html
[2] https://github.com/leeoniya/domvm/blob/2.x-dev/src/view/initElementNode.js#L84-L91

**Comment by leeoniya** [comment]
this checklist is mostly complete. the rest of the items will be added at a later time, if necessary.
